src/objects/Expense__c.object
<CustomObject>
    <description>Expenses accrued in relation to a DUG, one of its Meetups, or other related activities</description>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Date Expense Was Incurred</description>
        <inlineHelpText>Date Expense Was Incurred</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Line_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Line Item</label>
        <referenceTo>InvoiceLineItem__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Meetup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Meetup (if any) that this Expense relates to.</description>
        <inlineHelpText>The Meetup (if any) that this Expense relates to.</inlineHelpText>
        <label>Meetup</label>
        <referenceTo>Meetup__c</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>Exp-{000000}</displayFormat>
        <label>Expense Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>An Invoice to submit expenses related to a DUG for reimbursement.</description>
    <fields>
        <fullName>Date__c</fullName>
        <description>Date of Invoice</description>
        <inlineHelpText>Date of Invoice</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>InvoiceNumber__c</fullName>
        <defaultValue>TEXT(MONTH(TODAY()))+&apos;/&apos;
+
TEXT(DAY(TODAY()))+&apos;/&apos;
+
TEXT(YEAR(TODAY()))</defaultValue>
        <label>Invoice #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Inv-{0000}</displayFormat>
        <label>Invoice AutoNum</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/InvoiceLineItem__c.object
<CustomObject>
    <description>A Line Item on an Invoice submitting reimbursable expenses for a DUG</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>Amount</description>
        <inlineHelpText>Amount</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{000000}</displayFormat>
        <label>Invoice Line Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Meetup__c.object
<CustomObject>
    <description>A meeting (or event) that can act in a more robust way than the standard Event SObject.</description>
    <label>Meetup</label>
    <nameField>
        <label>Meetup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meetups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoiceFromMeetup.cls
public class InvoiceFromMeetup{
    public Meetup__c meetup{get; set;}
    public Expense__c[] meetupExpenses{get; set;}
    public Invoice__c newInvoice{get; set;}
    public InvoiceLineItem__c[] invLineItems{get; set;}

    public ApexPages.StandardController stdCtrlr{get; set;}
    
    public InvoiceFromMeetup(ApexPages.StandardController stdCtrlr){
        this.meetup = (Meetup__c)stdCtrlr.getRecord();
        this.meetupExpenses = 
                            [
                            SELECT Id, Name, Description__c, Amount__c, Date__c, 
                                   Invoice_Line_Item__c 
                            FROM Expense__c 
                            WHERE Meetup__c = :this.meetup.Id
                            ORDER BY Date__c ASC,
                                     Amount__c DESC
                            ];
    }

    public PageReference generateInvoice() {
        // Generate Invoice from Meetup
        this.newInvoice = new Invoice__c(
            Date__c = Date.today(),
            InvoiceNumber__c = String.valueOf(this.newInvoice.Date__c)
            // bill to should default on trigger
        );
        insert this.newInvoice;

        this.meetupExpenses = [
            SELECT Id, Name, Amount__c, Date__c, Description__c, Invoice_Line_Item__c
            FROM   Expense__c
            WHERE  Meetup__c = :this.meetup.Id
        ];
        generateLineItems();
        return new PageReference('/'+this.newInvoice.Id);
    }

    private void generateLineItems() {
        this.invLineItems = new InvoiceLineItem__c[]{};
        for(Expense__c meetupExpense : this.meetupExpenses){
            InvoiceLineItem__c invLineItem = new InvoiceLineItem__c();
            invLineItem.Invoice__c = this.newInvoice.Id;
            invLineItem.Amount__c = meetupExpense.Amount__c;
            invLineItem.Description__c = meetupExpense.Description__c;
            this.invLineItems.add(invLineItem);
        }
    }
}